### PR TITLE
Fix maximum firmware flash size.

### PR DESCRIPTION
**Pull request by 3d-gussner**
As this have been changed in https://github.com/mkbel/PF-build-env/commit/595cc4fb4d26c0cb22ae5d481be7866ab52f282f
I think it belongs also here as users using Arduino IDE 1.8.5 GUI version should have the same build environment as Prusa uses in `build.sh` and we in `PF-build.sh`

Changes are made to prusa3drambo-1.0.0\boards.txt

Value of `rambo.upload.maximum_size=258048` changed to `253952`

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@DRracer Just curious why don't you have the `U8glib` library from  https://github.com/ultimachine/ArduinoAddons/tree/master/rambo included? Isn't that used anymore or wasn't ever?

**Comment by 3d-gussner** [comment]
@DRracer Wouldn't it be possible to have the `avr6.xn` library change made by @mkbel (2nd language) included in here? Ultimachine did it with the `U8glib` library.

**Review by DRracer — APPROVED** [review]

**Comment by DRracer** [comment]
@3d-gussner it works without U8glib. It looks like wasn't used in the firmware at all.
avr6.xn: we'd love to have it here, it would solve a lot of confusion. Do you have an idea where to put it so that Arduino IDE accepts it?
Btw. we'll be moving this board definition into prusa3d repo shortly so there will be one more change to JSON paths.

**Comment by 3d-gussner** [comment]
> @3d-gussner it works without U8glib. It looks like wasn't used in the firmware at all.

I also couldn't find it anywhere, so we are fine.

> avr6.xn: we'd love to have it here, it would solve a lot of confusion. Do you have an idea where to put it so that Arduino IDE accepts it?

At this moment I solved it by `unzip` and/or `copy` the file in `PF-build.sh` using my modified `PF-buil-env` repository.

It would be great if we could have it in the JSON file. Have to look into that.

> Btw. we'll be moving this board definition into prusa3d repo shortly so there will be one more change to JSON paths.

Cool

**Comment by 3d-gussner** [comment]
> @3d-gussner it works without U8glib. It looks like wasn't used in the firmware at all.

I also couldn't find it anywhere, so we are fine.

> avr6.xn: we'd love to have it here, it would solve a lot of confusion. Do you have an idea where to put it so that Arduino IDE accepts it?

At this moment I solved it by `unzip` and/or `copy` the file in `PF-build.sh` using my modified `PF-buil-env` repository.

It would be great if we could have it in the JSON file. Have to look into that.

> Btw. we'll be moving this board definition into prusa3d repo shortly so there will be one more change to JSON paths.

Cool

**Comment by 3d-gussner** [comment]
> @3d-gussner it works without U8glib. It looks like wasn't used in the firmware at all.

I also couldn't find it anywhere, so we are fine.

> avr6.xn: we'd love to have it here, it would solve a lot of confusion. Do you have an idea where to put it so that Arduino IDE accepts it?

At this moment I solved it by `unzip` and/or `copy` the file in `PF-build.sh` using my modified `PF-buil-env` repository.

It would be great if we could have it in the JSON file. Have to look into that.

> Btw. we'll be moving this board definition into prusa3d repo shortly so there will be one more change to JSON paths.

Cool

**Comment by 3d-gussner** [comment]
> @3d-gussner it works without U8glib. It looks like wasn't used in the firmware at all.

I also couldn't find it anywhere, so we are fine.

> avr6.xn: we'd love to have it here, it would solve a lot of confusion. Do you have an idea where to put it so that Arduino IDE accepts it?

At this moment I solved it by `unzip` and/or `copy` the file in `PF-build.sh` using my modified `PF-buil-env` repository.

It would be great if we could have it in the JSON file. Have to look into that.

> Btw. we'll be moving this board definition into prusa3d repo shortly so there will be one more change to JSON paths.

Cool

**Comment by 3d-gussner** [comment]
> @3d-gussner it works without U8glib. It looks like wasn't used in the firmware at all.

I also couldn't find it anywhere, so we are fine.

> avr6.xn: we'd love to have it here, it would solve a lot of confusion. Do you have an idea where to put it so that Arduino IDE accepts it?

At this moment I solved it by `unzip` and/or `copy` the file in `PF-build.sh` using my modified `PF-buil-env` repository.

It would be great if we could have it in the JSON file. Have to look into that.

> Btw. we'll be moving this board definition into prusa3d repo shortly so there will be one more change to JSON paths.

Cool

**Comment by 3d-gussner** [comment]
Hi @DRracer , started with a new version https://github.com/3d-gussner/Arduino_Boards/tree/Bootloader
- added bootloader
- added tools download

Next step is to modify the avr-gcc `avr6.xn` file and provide the download file.

Tried to compile manually with fresh Arduino IDE 1.8.5 portable just with new JSON (and manual change of `avr6.xn`) and the results look promising. Board and Tools have been downloaded automatically.
Also with Arduino IDE 1.8.8 it used the "old" avr-gcc ... but there build size was bit lager, guess newer library.

The Tools aren't part of the Arduino source code, hoped to find it there. But when I build Arduino IDE I can see that the tools are downloaded. So more investigation needed.

**Pull request merged**
